---
- hosts: all
  sudo: yes
  roles:
    - geth
  environment:
    PATH: "/usr/local/go/bin:/usr/bin:/bin"
  tasks:
    - name: systemd
      template: src="templates/geth.service.j2" dest="/etc/systemd/system/geth.service" owner=root group=root
